### ISSUE TITLE
Program doesn't exit normally after execution

### ISSUE THREAD

**Issue by testphreak** [EMCECS/nfs-client-java#20] opened 2018-02-01 02:51 UTC
Hi @DavidASeibert, thank you for the excellent NFSv3 Java client. I just started using it to test read/write access to an NFS share. I wrote a short program to test read access. Something odd I notice, is that the program doesn't exit normally. Can't figure out why and I have to exit the program manually. Any idea why this might be happening? I am using JDK `1.8.0_131` on Mac OS X (Sierra).

```java
public class NFSClient {

    public static void main(String args[]) {
        try {

            Nfs3 nfs3 = new Nfs3("10.x.x.x", "/testdir/",
                    new CredentialUnix(0, 0, null), 3);

            Nfs3File nfs3File = new Nfs3File(nfs3, "/testsubdir/");

            if (nfs3File.canRead()) {
                System.out.println(nfs3File.listFiles());
            } else {
                System.out.println("No read permission");
            }

        } catch (IOException e) {
            System.out.println(e);
        }
    }
}
```
I am able to establish a connection and list the files in the program above, but can't figure out why it won't exit. Please let me know if you need more information.

**Additional information**:
The NFS share is a [AWS Storage File Gateway](https://aws.amazon.com/storagegateway/file/), which offers NFS mount for S3.

**Comment by testphreak** [comment] 2018-02-01 19:18
The only way I have found so far to ensure the program exits, is by shutting down `NetMgr`:

```java
finally {
   NetMgr.getInstance().shutdown();
}
```

**Comment by DavidASeibert** [comment] 2018-02-01 20:06
Thanks, @testphreak. I will investigate.

**Comment by brunchboy** [comment] 2018-11-08 02:51
It sounds like the `NetMgr` creates one or more threads that should really be [marked as daemon threads](https://docs.oracle.com/javase/7/docs/api/java/lang/Thread.html#setDaemon(boolean)) before starting them, as they are not supposed to prevent program termination.

**Comment by brunchboy** [comment] 2018-11-08 03:40
To be specific, the problem is here: https://github.com/EMCECS/nfs-client-java/blob/master/src/main/java/com/emc/ecs/nfsclient/network/NetMgr.java#L67-L68

This code should be calling the version of `newCachedThreadPool()` which takes a `ThreadFactory` argument, and passing in a `ThreadFactory` that sets the created threads to be daemon threads, an example of which is shown in this answer: https://stackoverflow.com/questions/13883293/turning-an-executorservice-to-daemon-in-java

(Note that this needs to be done for both `newCachedThreadPool()` calls.)

**Comment by DavidASeibert** [comment] 2018-11-27 19:06
Fixed in master after PR merge.

**Closed by DavidASeibert** 2018-11-27 19:06 UTC
