### ISSUE TITLE
problem port 111

### ISSUE THREAD

**Issue by AveiShriety** [EMCECS/nfs-client-java#15] opened 2017-06-07 03:30 UTC
problem such as 
_WARN network.ClientIOHandler - Channel disconnected: /192.168.201.60:111_
_WARN network.ClientIOHandler - Channel closed: /192.168.201.60:111_

what to cause this matter? please help 3q!!
@DavidASeibert @jasoncwik

**Comment by DavidASeibert** [comment] 2017-06-07 14:15
@AveiShriety 111 is the port for the RPC port mapping utility. This utility needs to be running so that the client can find the NFS service port, which can vary from system to system. My guess is that this service is not running, or your client does not have permission to use it (much less likely), although you have not posted enough information for me to be certain.

**Comment by AveiShriety** [comment] 2017-06-08 02:02
@DavidASeibert   The premise is that I have already made my java code connected to the NFS server with no problems and warns. 
_WARN network.ClientIOHandler - Channel disconnected: /192.168.201.60:111_
_WARN network.ClientIOHandler - Channel closed: /192.168.201.60:111_
These two warns occur when I do nothing( no operation on file with java IO, such as read or write ) for a few minutes after my java code connected to the NFS server

**Comment by DavidASeibert** [comment] 2017-06-08 13:16
@AveiShriety This channel is being disconnected because no calls are using it. It is only used to get service ports during the initialization of the nfs client, and when stale file handles are being refreshed. The warning is minor and can be ignored unless you are seeing other problems with the client. Even if you are seeing other problems with the client, they are most likely not the cause of those problems. If you are seeing other problems, what are they?

**Comment by DavidASeibert** [comment] 2017-08-16 18:36
No actual problems have been observed, so I will close this issue.

**Closed by DavidASeibert** 2017-08-16 18:36 UTC
